Repository kanakaraju234/react-thunk, pull requests merged in 2024-04, with the labels that each got.

#21 PR:Register signup page
  db.json
  src/App.css
  src/App.js
  src/bookings/Dashboard.jsx
  src/components/Layout.jsx
  src/components/Login.jsx
  src/components/Signup.jsx
  src/redux/Reducers/UserReducer.js
Labels: In Development

#27 Pagination and 404 error
  db.json
  public/index.html
  public/logo1.svg
  public/manifest.json
  src/App.js
  src/components/404.jsx
  src/components/Layout.css
  src/components/Users.css
  src/components/Users.jsx
  src/core/Pagination.css
  src/core/Pagination.jsx
  src/images/404.svg
  src/redux/Reducers/UserReducer.js
Labels: Todo

#30 PR:text_color-changed
  src/components/Users.jsx
Labels: bug

#32 userlist color changed to red
  src/components/Users.jsx
Labels: bug

#33 PR:Usercard changes
  src/components/Users.jsx
Labels: bug

#34 PR:userlist_text-modified
  src/components/Users.jsx
Labels: bug

#35 data has been updated
  src/components/Users.jsx
Labels: bug

#36 datamain updated
  src/components/Users.jsx
Labels: bug

#37 PR:number_added-to-userlist
  src/components/Users.jsx
Labels: bug
